deployment:
  tasks:
    - export DEPLOYPATH=/home/divermin/repositories/divermidteam/public_html/
    # Copiar todo el contenido de public a public_html
    - /bin/cp -R public/* "$DEPLOYPATH"
    # Copiar el archivo index.php modificado (que debe estar en la raíz)
    - /bin/cp index.php "$DEPLOYPATH/index.php"
